name: è‡ªåŠ¨éƒ¨ç½²åˆ° CF Worker

on:
  push:
    branches:
      - main
    paths:
      - '_worker-all.js'
  workflow_dispatch:

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    env:
      ADMIN: ${{ vars.ADMIN }}
      PASSWORD: ${{ vars.PASSWORD }}
      CF_KV_ID: ${{ vars.CF_KV_ID }}
    
    steps:
      - name: â¬‡ï¸ æ£€å‡ºä»“åº“
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ å®‰è£… Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ†™ æ›´æ–°å¹¶å®‰è£…æœ€æ–° Wrangler
        run: npm install -g wrangler@latest
    
      - name: ğŸ”„ æ›¿æ¢ wrangler.toml ä¸­çš„å˜é‡
        id: config_setup
        run: |
          sed -i "s#{CF_KV_ID}#${CF_KV_ID}#g" wrangler.toml
          
          WORKER_NAME=$(grep '^name =' wrangler.toml | awk -F '"' '{print $2}')
          if [ -z "$WORKER_NAME" ]; then
            echo "ğŸ”´ é”™è¯¯: æœªèƒ½åœ¨ wrangler.toml ä¸­æ‰¾åˆ° 'name' å­—æ®µ"; exit 1
          fi
          
          echo -e "\nğŸ‰ é¡¹ç›®é…ç½®ä¿¡æ¯å¦‚ä¸‹:"
          echo "------------------"
          cat wrangler.toml
          echo "------------------"
          echo "worker_name=$WORKER_NAME" >> $GITHUB_OUTPUT

      - name: âš™ï¸ æ£€æŸ¥å¹¶ç”Ÿæˆ wrangler vars
        id: dynamic_vars
        run: |
          VARS=""
          [ -n "$ADMIN" ] && VARS+="ADMIN"$'\n'
          [ -n "$PASSWORD" ] && VARS+="PASSWORD"$'\n'

          if [ -n "$VARS" ]; then
            printf 'vars_list<<EOF\n%sEOF\n' "$VARS" >>"$GITHUB_OUTPUT"
            echo "âœ… ä¼ é€’ç»™ wrangler çš„å˜é‡:"
            printf '%s' "$VARS"
          else
            echo "âš ï¸ æ²¡æœ‰éœ€è¦ä¼ é€’çš„å˜é‡"
            printf 'vars_list=\n' >>"$GITHUB_OUTPUT"
          fi
          
      - name: ğŸš€ éƒ¨ç½²åˆ° CF Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ vars.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          vars: ${{ steps.dynamic_vars.outputs.vars_list }}
          
      - name: âœ¨ è¾“å‡º Worker ç®¡ç†åå°
        env:
          WORKER_NAME: ${{ steps.config_setup.outputs.worker_name }}
          ACCOUNT_ID: ${{ vars.CF_ACCOUNT_ID }}
        run: |
          echo -e "\nâœ¨ éƒ¨ç½²å®Œæˆ"
          echo "ğŸŒ ç‚¹å‡»ä»¥ä¸‹é“¾æ¥å¯è®¿é—®é¡¹ç›®ç®¡ç†åå°"
          echo "https://dash.cloudflare.com/${ACCOUNT_ID}/workers/services/view/${WORKER_NAME}/production/settings"
          echo "ğŸš€ å»ºè®®: ç»™é¡¹ç›®ç»‘å®šä¸€ä¸ªè‡ªå®šä¹‰åŸŸå"
          
